accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login_user, name='login'),
    path('profile/', views.user_profile, name='profile'),
    path('logout/', views.logout_user, name='logout'),

]

log_visualizer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('logs/', include('logs.urls', namespace='logs')),
]

logs/urls.py
from django.urls import path

from . import views

app_name = 'logs'

urlpatterns = [
    path('', views.visualize, name='dashboard'),
    path('chart/category/', views.category_count, name='category-count'),
    path('chart/log-count/', views.log_count, name='log-count'),
]

accounts/models.py
from django.db import models

# Create your models here.

logs/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    created_on = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ['name']

    def __str__(self):
        return self.name


class Log(models.Model):
    timestamp = models.DateTimeField()

    message = models.CharField(max_length=1000)

    category = models.ForeignKey(
        Category,
        related_name='logs',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    created_on = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )

    class Meta:
        verbose_name = 'log'
        verbose_name_plural = 'logs'
        ordering = ['-timestamp']

    def __str__(self):
        return self.message

accounts/forms.py
from django.contrib.auth.forms import PasswordChangeForm


class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Old password',
        })

        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'New password',
        })

        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Confirm New Password',
        })

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from accounts.forms import CustomPasswordChangeForm


def login_user(request):
    if request.user.is_authenticated:
        return redirect('accounts:profile')

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        # todo: validate
        if not username or not password:
            print('Incorrect username or password')
            messages.error(request, 'Incorrect username or password')
            return render(request, 'accounts/login_form.html')

        user = authenticate(request, username=username, password=password)

        if not user:
            messages.error(request, 'Incorrect username or password')
            return render(request, 'accounts/login_form.html')

        # login user
        login(request, user)
        return redirect('accounts:profile')

    return render(request, 'accounts/login_form.html')


@login_required(login_url='accounts:login')
def user_profile(request):
    form = CustomPasswordChangeForm(user=request.user, data=request.POST or None)

    if request.method == 'POST':
        if not form.is_valid():
            return render(request, 'accounts/user_profile.html', {'form': form})

        # save valid password, update session, redirect to same page with msg
        form.save()
        update_session_auth_hash(request, form.user)

        messages.success(request, 'Password changed')
        return redirect('accounts:profile')

    return render(request, 'accounts/user_profile.html', {'form': form})


def logout_user(request):
    logout(request)
    return redirect('accounts:login')

logs/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render

from logs.models import Log, Category


@login_required(login_url='accounts:login')
def visualize(request):
    logs = Log.objects.only(
        'timestamp',
        'message',
        'category__name',
    ).select_related("category").order_by('-timestamp')[:10]

    return render(request, 'logs/index.html', {'logs': logs})


@login_required(login_url='accounts:login')
def log_count(request):
    _log_count = Log.objects.all().values('timestamp').annotate(count=Count('pk', distinct=True))

    _data = [{'name': lc.get('timestamp').strftime("%b %d %H:%M:%S"), 'y': lc.get('count')} for lc in _log_count]

    return JsonResponse({'log_count': _data})


@login_required(login_url='accounts:login')
def category_count(request):
    # sort: largest -> smallest
    categories = Category.objects.all().annotate(logs_count=Count('logs')).order_by('-logs_count')

    # format data for highcharts
    _data = [{'name': i.name, 'y': i.logs_count} for i in categories]

    return JsonResponse({'categories': _data})

accounts/templates/accounts/login_form.html
{% extends 'base.html' %}

{% block content %}

<div class="row height-full">

    <div class="d-flex align-items-center justify-content-center">


        <div class="col-md-4 rounded p-4 bg-lightblue">

            <h1 class="fs-4">Login</h1>

            <form method="POST" action="{% url 'accounts:login' %}">
                {% csrf_token %}

                <div class="mb-2">
                    <label for="username" class="form-label">Username</label>
                    <input name="username" type="text" class="form-control" id="username" placeholder="Username">
                </div>

                <div class="mb-4">
                    <label for="password" class="form-label">Password</label>
                    <input name="password" type="password" class="form-control" id="password" placeholder="Password">
                </div>

                <!-- error messages -->
                {% if messages %}
                {% for message in messages %}
                <div class="alert {% if message.tags == 'error' %} alert-danger{% endif %}">{{ message|safe }}</div>
                {% endfor %}
                {% endif %}

                <div class="col-12">
                    <button type="submit" class="btn btn-primary w-100">Sign in</button>
                </div>

            </form>

        </div>


    </div>

    {% endblock %}

accounts/templates/accounts/user_profile.html
{% extends 'base.html' %}

{% block title %}
{{request.user}} - Profile
{% endblock %}

{% block content %}

<div class="row height-full">

    <div class="d-flex mt-5">


        <!-- user info section -->
        <div class="" style="flex:1;">

            <h1>Hello, {{request.user}}!</h1>

            {% if form.errors %}
            <div class="w-75 ms-md-5 mt-5 alert alert-danger">
                <h4>Please fix the following errors</h4>
                <ul>
                    {% for field in form %}
                    {% if field.errors %}
                    {% for error in field.errors %}
                    <li>{{ error|escape }}</li>
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                </ul>
                {% if form.non_field_errors %}
                {{ form.non_field_errors }}
                {% endif %}
            </div>
            {% endif %}

            {% if messages %}
            <div class="w-75 ms-md-5 mt-5 alert alert-secondary">
                <ul>
                    {% for msg in messages %}
                    <li>{{ msg }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}


        </div>

        <!-- change password section -->
        <div class="" style="flex:1;">

            <div class="p-4">

                <h3>Change your password</h3>

                <form method="POST" action="{% url 'accounts:profile' %}">

                    {% csrf_token %}

                    <div class="mb-2">
                        <label for="old_password" class="form-label">Old Password</label>
                        {{ form.old_password }}
                    </div>

                    <div class="mb-2">
                        <label for="new_password1" class="form-label">New Password</label>
                        {{ form.new_password1 }}
                    </div>

                    <div class="mb-2">
                        <label for="new_password2" class="form-label">Password Again</label>
                        {{ form.new_password2 }}
                    </div>

                    <div class="col-12">
                        <button type="submit" class="btn btn-primary w-100">Change Password</button>
                    </div>

                </form>

            </div>

        </div>


    </div>


</div>

{% endblock %}

logs/templates/logs/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Logs
{% endblock %}

{% block content %}

<!-- chart area -->
<div class="row">

    <!-- line chart -->
    <div class="col-12 col-md-6" style="">

        <div id="line-chart"></div>

    </div>


    <!-- pie chart -->
    <div class="col-12 col-md-6" style="">

        <div id="pie-chart"></div>

    </div>

</div>
<!-- end: chart area -->

<hr>


<!-- table area -->

<div class="row my-5" style="">

    <h5 class="mb-2">Latest logs</h5>

    <table class="table table-striped">

        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Timestamp</th>
            <th scope="col">Category</th>
            <th scope="col">Message</th>
        </tr>
        </thead>

        <tbody>

        {% for l in logs %}
        <!-- table row -->
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ l.timestamp|date:"M d H:i:s" }}</td>
            <td>{{ l.category }}</td>
            <td>{{ l.message }}</td>
        </tr>
        <!-- end: table row -->
        {% endfor %}


        </tbody>
    </table>

</div>

<!-- end: table area -->

{% endblock %}


{% block scripts %}

<!-- highcharts -->
<script language="javascript" type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>

<!-- highcharts util functions -->
<script language="javascript" type="text/javascript" src="{% static 'scripts.js' %}"></script>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- bootstrap cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- custom CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}"/>

    <title>{% block title %}Log Visualizer{% endblock %}</title>
</head>

<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-dark navbar-dark py-1 fixed-top">
    <div class="container">
        <a href="/" class="navbar-brand">Log Visualizer</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navmenu">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'logs:dashboard' %}" class="nav-link">Log</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'accounts:profile' %}" class="nav-link">Profile</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'accounts:logout' %}" class="nav-link">Sign out</a>
                </li>

                {% else %}

                <li class="nav-item">
                    <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<!-- End: Navbar -->

<!-- main container -->
<div class="container">
    {% block content %}{% endblock %}
</div>
<!-- end: main container -->

<!-- footer -->
<footer class="d-flex justify-content-center align-items-center py-5 border-top">
    <span class="text-muted me-2">Log Visualizer</span>
</footer>
<!-- end: footer -->


<!-- js -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

{% block scripts%}{% endblock %}


</body>

</html>